/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e9e1dc",
        "on-tertiary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#a3f69c",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#872000",
        "error": "#ba1a1a",
        "surface-container-high": "#efe6e2",
        "surface-container-low": "#fbf2ed",
        "on-primary-container": "#fffbff",
        "on-background": "#1e1b18",
        "inverse-on-surface": "#f8efea",
        "surface-tint": "#b12d00",
        "tertiary-container": "#956e00",
        "on-tertiary": "#ffffff",
        "secondary": "#1b6d24",
        "on-secondary-fixed-variant": "#005312",
        "primary": "#ad2c00",
        "on-secondary-container": "#217128",
        "surface-bright": "#fff8f5",
        "on-primary-fixed": "#3b0900",
        "outline-variant": "#e3bfb2",
        "outline": "#8f7066",
        "on-secondary-fixed": "#002204",
        "inverse-surface": "#34302c",
        "on-error-container": "#93000a",
        "surface": "#fff8f5",
        "tertiary": "#765700",
        "secondary-container": "#a0f399",
        "primary-fixed-dim": "#ffb5a0",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-surface-variant": "#5a4138",
        "background": "#fff8f5",
        "tertiary-fixed": "#ffdfa0",
        "primary-fixed": "#ffdbd1",
        "surface-container": "#f5ece7",
        "on-tertiary-fixed": "#261a00",
        "on-surface": "#1e1b18",
        "inverse-primary": "#ffb5a0",
        "tertiary-fixed-dim": "#f8bd2a",
        "secondary-fixed-dim": "#88d982",
        "on-secondary": "#ffffff",
        "surface-dim": "#e1d8d4",
        "surface-container-highest": "#e9e1dc",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}